export enum EstadoPedido {
  A_CONFIRMAR = "A_CONFIRMAR",
  EN_PREPARACION = "EN_PREPARACION",
  LISTO = "LISTO",
  EN_CAMINO = "EN_CAMINO",
  ENTREGADO = "ENTREGADO",
  CANCELADO = "CANCELADO",
  RECHAZADO = "RECHAZADO",
}
